package com.khw.studnet_grade.entity;

import lombok.Data;

@Data
public class Middle {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column middle.middleid
     *
     * @mbggenerated Mon Dec 28 16:11:42 CST 2020
     */
    private Integer middleid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column middle.cno
     *
     * @mbggenerated Mon Dec 28 16:11:42 CST 2020
     */
    private Integer cno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column middle.tno
     *
     * @mbggenerated Mon Dec 28 16:11:42 CST 2020
     */
    private Integer tno;

    public Middle() {
    }

    public Middle(Integer middleid, Integer cno, Integer tno) {
        this.middleid = middleid;
        this.cno = cno;
        this.tno = tno;
    }

    public Middle(Integer cno, Integer tno) {
        this.cno = cno;
        this.tno = tno;
    }

    @Override
    public String toString() {
        return "Middle{" +
                "middleid=" + middleid +
                ", cno=" + cno +
                ", tno=" + tno +
                '}';
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column middle.middleid
     *
     * @return the value of middle.middleid
     * @mbggenerated Mon Dec 28 16:11:42 CST 2020
     */
    public Integer getMiddleid() {
        return middleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column middle.middleid
     *
     * @param middleid the value for middle.middleid
     * @mbggenerated Mon Dec 28 16:11:42 CST 2020
     */
    public void setMiddleid(Integer middleid) {
        this.middleid = middleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column middle.cno
     *
     * @return the value of middle.cno
     * @mbggenerated Mon Dec 28 16:11:42 CST 2020
     */
    public Integer getCno() {
        return cno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column middle.cno
     *
     * @param cno the value for middle.cno
     * @mbggenerated Mon Dec 28 16:11:42 CST 2020
     */
    public void setCno(Integer cno) {
        this.cno = cno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column middle.tno
     *
     * @return the value of middle.tno
     * @mbggenerated Mon Dec 28 16:11:42 CST 2020
     */
    public Integer getTno() {
        return tno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column middle.tno
     *
     * @param tno the value for middle.tno
     * @mbggenerated Mon Dec 28 16:11:42 CST 2020
     */
    public void setTno(Integer tno) {
        this.tno = tno;
    }
}