package com.khw.studnet_grade.entity;

public class Student {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.sno
     *
     * @mbggenerated Mon Dec 28 13:58:29 CST 2020
     */
    private Integer sno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.sname
     *
     * @mbggenerated Mon Dec 28 13:58:29 CST 2020
     */
    private String sname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.sage
     *
     * @mbggenerated Mon Dec 28 13:58:29 CST 2020
     */
    private String sage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.phone
     *
     * @mbggenerated Mon Dec 28 13:58:29 CST 2020
     */
    private String phone;

    public Student() {
    }

    public Student(Integer sno, String sname, String sage, String phone) {
        this.sno = sno;
        this.sname = sname;
        this.sage = sage;
        this.phone = phone;
    }

    public Student(Integer sno, String sname, String sage) {
        this.sno = sno;
        this.sname = sname;
        this.sage = sage;
    }

    @Override
    public String toString() {
        return "Student{" +
                "sno=" + sno +
                ", sname='" + sname + '\'' +
                ", sage='" + sage + '\'' +
                ", phone='" + phone + '\'' +
                '}';
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.sno
     *
     * @return the value of student.sno
     * @mbggenerated Mon Dec 28 13:58:29 CST 2020
     */
    public Integer getSno() {
        return sno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.sno
     *
     * @param sno the value for student.sno
     * @mbggenerated Mon Dec 28 13:58:29 CST 2020
     */
    public void setSno(Integer sno) {
        this.sno = sno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.sname
     *
     * @return the value of student.sname
     * @mbggenerated Mon Dec 28 13:58:29 CST 2020
     */
    public String getSname() {
        return sname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.sname
     *
     * @param sname the value for student.sname
     * @mbggenerated Mon Dec 28 13:58:29 CST 2020
     */
    public void setSname(String sname) {
        this.sname = sname == null ? null : sname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.sage
     *
     * @return the value of student.sage
     * @mbggenerated Mon Dec 28 13:58:29 CST 2020
     */
    public String getSage() {
        return sage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.sage
     *
     * @param sage the value for student.sage
     * @mbggenerated Mon Dec 28 13:58:29 CST 2020
     */
    public void setSage(String sage) {
        this.sage = sage == null ? null : sage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.phone
     *
     * @return the value of student.phone
     * @mbggenerated Mon Dec 28 13:58:29 CST 2020
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.phone
     *
     * @param phone the value for student.phone
     * @mbggenerated Mon Dec 28 13:58:29 CST 2020
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }
}