package com.khw.studnet_grade.entity;

import lombok.Data;

@Data
public class Teacher {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher.tno
     *
     * @mbggenerated Mon Dec 28 13:57:12 CST 2020
     */
    private Integer tno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher.tname
     *
     * @mbggenerated Mon Dec 28 13:57:12 CST 2020
     */
    private String tname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher.age
     *
     * @mbggenerated Mon Dec 28 13:57:12 CST 2020
     */
    private Integer age;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher.sex
     *
     * @mbggenerated Mon Dec 28 13:57:12 CST 2020
     */
    private Integer sex;

    public Teacher() {
    }

    public Teacher(Integer tno, String tname, Integer age, Integer sex) {
        this.tno = tno;
        this.tname = tname;
        this.age = age;
        this.sex = sex;
    }

    public Teacher(Integer tno, String tname) {
        this.tno = tno;
        this.tname = tname;
    }

    @Override
    public String toString() {
        return "Teacher{" +
                "tno=" + tno +
                ", tname='" + tname + '\'' +
                ", age=" + age +
                ", sex=" + sex +
                '}';
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher.tno
     *
     * @return the value of teacher.tno
     * @mbggenerated Mon Dec 28 13:57:12 CST 2020
     */
    public Integer getTno() {
        return tno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher.tno
     *
     * @param tno the value for teacher.tno
     * @mbggenerated Mon Dec 28 13:57:12 CST 2020
     */
    public void setTno(Integer tno) {
        this.tno = tno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher.tname
     *
     * @return the value of teacher.tname
     * @mbggenerated Mon Dec 28 13:57:12 CST 2020
     */
    public String getTname() {
        return tname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher.tname
     *
     * @param tname the value for teacher.tname
     * @mbggenerated Mon Dec 28 13:57:12 CST 2020
     */
    public void setTname(String tname) {
        this.tname = tname == null ? null : tname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher.age
     *
     * @return the value of teacher.age
     * @mbggenerated Mon Dec 28 13:57:12 CST 2020
     */
    public Integer getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher.age
     *
     * @param age the value for teacher.age
     * @mbggenerated Mon Dec 28 13:57:12 CST 2020
     */
    public void setAge(Integer age) {
        this.age = age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher.sex
     *
     * @return the value of teacher.sex
     * @mbggenerated Mon Dec 28 13:57:12 CST 2020
     */
    public Integer getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher.sex
     *
     * @param sex the value for teacher.sex
     * @mbggenerated Mon Dec 28 13:57:12 CST 2020
     */
    public void setSex(Integer sex) {
        this.sex = sex;
    }
}