package com.khw.studnet_grade.mapper;

import com.khw.studnet_grade.entity.Middle;
import com.khw.studnet_grade.entity.MiddleExample;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import java.util.List;

@Mapper
@Repository
public interface MiddleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table middle
     *
     * @mbggenerated Mon Dec 28 16:11:42 CST 2020
     */
    int countByExample(MiddleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table middle
     *
     * @mbggenerated Mon Dec 28 16:11:42 CST 2020
     */
    int deleteByExample(MiddleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table middle
     *
     * @mbggenerated Mon Dec 28 16:11:42 CST 2020
     */
    int deleteByPrimaryKey(Integer middleid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table middle
     *
     * @mbggenerated Mon Dec 28 16:11:42 CST 2020
     */
    int insert(Middle record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table middle
     *
     * @mbggenerated Mon Dec 28 16:11:42 CST 2020
     */
    int insertSelective(Middle record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table middle
     *
     * @mbggenerated Mon Dec 28 16:11:42 CST 2020
     */
    List<Middle> selectByExample(MiddleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table middle
     *
     * @mbggenerated Mon Dec 28 16:11:42 CST 2020
     */
    Middle selectByPrimaryKey(Integer middleid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table middle
     *
     * @mbggenerated Mon Dec 28 16:11:42 CST 2020
     */
    int updateByExampleSelective(@Param("record") Middle record, @Param("example") MiddleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table middle
     *
     * @mbggenerated Mon Dec 28 16:11:42 CST 2020
     */
    int updateByExample(@Param("record") Middle record, @Param("example") MiddleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table middle
     *
     * @mbggenerated Mon Dec 28 16:11:42 CST 2020
     */
    int updateByPrimaryKeySelective(Middle record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table middle
     *
     * @mbggenerated Mon Dec 28 16:11:42 CST 2020
     */
    int updateByPrimaryKey(Middle record);
}